server:
  port : 8083
spring:
  resources :
    add-mappings : true
  datasource: #h2 생성할 DB 기본 정보
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    datasource: h2
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: false
    hibernate :
      ddl-auto : none
  h2:
    console:
      enabled: true
      path: /h2