DROP TABLE IF EXISTS COUPON;
CREATE TABLE COUPON (
    ID VARCHAR(50) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    PERIOD INT NOT NULL,
    EXPIRE_DATE TIMESTAMP, --지급 시점
    USER_NO LONG,   --지급 시점
    USED BOOLEAN NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    USER_NO LONG NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    PRIMARY KEY (USER_NO)
);